name: Auto approve

on: pull_request

jobs:
  auto-approve:

    name: Auto approve Pull Request
    runs-on: ubuntu-latest

    steps:
    - name: Approve Dependency Update
      uses: hmarr/auto-approve-action@v2.4.0
      if: github.actor == 'renovate[bot]'
      with:
        github-token: "${{ secrets.ACCESS_TOKEN }}"
